my_url/my_url/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urlshortener.urls'))
]

my_url/urlshortener/urls.py
from django.urls import path
from .views import home_view, redirect_url_view, full_list, shortener_json, details, shortener_to_json

app_name="shortener"
urlpatterns = [
    path(
        '',
        home_view,
        name="home"
    ),
    path(
        'full_list/',
        full_list,
        name="full_list"
    ),
    path(
        '<str:short_url>',
        redirect_url_view,
        name='redirect'
    ),
    path(
        'details/<int:pk>/',
        details,
        name='details'
    ),
    path(
        'shortener_json/',
        shortener_to_json,
        name='shortener_json'
    ),
    path(
        'api/',
        shortener_json
    )
]

my_url/urlshortener/models.py
from django.db import models
from django.forms import model_to_dict
from .utils import create_shortened_url

# Create your models here.
class Shortener(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    long_url = models.URLField()
    short_url = models.CharField(max_length=20, unique=True, blank=True)
    times_clicked = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.long_url} to {self.short_url}'
    
    def to_json(self):
        item = model_to_dict(self)
        return item
    
    class Meta:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        if not self.short_url:
            self.short_url = create_shortened_url(self)
        super().save(*args, **kwargs)

class DetailShortener(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    browser = models.CharField(max_length=100, default='')
    url = models.ForeignKey(Shortener, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.url.short_url} from {self.browser}'
    
    def to_json(self):
        item = model_to_dict(self)
        return item
    
    class Meta:
        ordering = ['-created']
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

my_url/urlshortener/forms.py
from django import forms
from .models import Shortener

class ShortenerForm(forms.ModelForm):
    long_url = forms.URLField(
        widget=forms.URLInput(
            attrs={
                'class': 'form-control form-control-lg',
                'placeholder': 'Your URL to shorten'
                }
        )
    )

    class Meta:
        model = Shortener
        fields = ('long_url',)

my_url/urlshortener/views.py
import datetime
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
#Serializer
from rest_framework.exceptions import NotFound
from rest_framework.parsers import JSONParser
from rest_framework.decorators import api_view
from .models import Shortener, DetailShortener
from .forms import ShortenerForm
from .serializer import ShortenerSerializer

def home_view(request):
    template = 'home.html'
    context = {}
    context['form'] = ShortenerForm()

    if request.method == 'GET':
        context['full_list'] = Shortener.objects.all()

        return render(request, template, context)
    elif request.method == 'POST':
        my_form=ShortenerForm(request.POST)
        if my_form.is_valid():
            url_object = my_form.save()
            new_url = request.build_absolute_uri('/')+url_object.short_url
            long_url = url_object.long_url
            context['new_url'] = new_url
            context['long_url'] = long_url
        context['errors'] = my_form.errors

        return render(request, template, context)

def full_list(request):
    template = 'full_list.html'
    context = {}
    context['full_list'] = Shortener.objects.all()

    return render(request, template, context)

def redirect_url_view(request, short_url):
    try:
        shortener = get_object_or_404(Shortener, short_url=short_url)
        shortener.times_clicked += 1
        shortener.save()
        user_agent = request.user_agent
        detail = DetailShortener(
            browser = user_agent.browser.family + ' ' + user_agent.browser.version_string,
            url_id = shortener.pk
        )
        detail.save()
        return HttpResponseRedirect(shortener.long_url)
    except:
        return render(request, '404.html', status=404)

def details(request, pk):
    template = 'details.html'
    context = {}
    
    try:
        shortener = Shortener.objects.get(pk=pk)
        details = DetailShortener.objects.filter(url_id=shortener.pk)
        context['url'] = shortener.long_url
        for d in details:
            print(d)
        context['details_url'] = details

        return render(request, template, context)
    except:
        return render(request, '404.html', status=404)

def shortener_to_json(request):
    data = {}
    if request.method == 'GET':
        data['data'] = []
        shortener = Shortener.objects.all().order_by('-id')[:10]
        for s in shortener:
            item = {
                'type': 'url',
                'id': s.id,
                'attributes': {
                    'created_at': s.created,
                    'original_url': s.long_url,
                    'url': request.build_absolute_uri('/') + s.short_url,
                    'clicks': s.times_clicked
                }
            }
            data['data'].append(item)
            item['relationships'] = []
            for d in DetailShortener.objects.filter(url_id=s.pk):
                item['relationships'].append({
                    'id': d.pk,
                    'browser': d.browser
                })
        return JsonResponse(data, safe=False)

@api_view(['GET'])
def shortener_json(request):
    if request.method == 'GET':
        data = []
        shortener = Shortener.objects.all().order_by('-id')[:10]
        for s in shortener:
            data.append(
                {
                    'type': 'url',
                    'id': s.pk,
                    'attributes': {
                        'created-at': s.created,
                        'original-url': s.long_url,
                        'url': s.short_url,
                        'clicks': s.times_clicked
                    },
                    'relationships': {
                        'metrics': {
                            'data': [
                                {
                                    'id': 'hola'
                                }
                            ]
                        }
                    }
                }
            )
        print(data)

        serializer = ShortenerSerializer(shortener, many=True)
        return JsonResponse(serializer.data, safe=False)

my_url/urlshortener/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Full Stack Labs Test</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
  </head>
  <body>
   
    {% block body %} 
    {% endblock body %}
    
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

my_url/urlshortener/templates/details.html
{% extends 'base.html' %} 
{% block body %}

<div class="container">
  <div class="card mt-5">
    <div class="card-header text-center py-3">
      <h1>Details of {{ url }}</h1>
    </div>
    <div class="px-3 py-4">
        <h3>Metrics</h3>
    </div>
    <div class="px-3 py-4">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Browser</th>
                        <th>Clicked Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for d in details_url %}
                    <tr>
                        <td>{{ d.browser }}</td>
                        <td>{{ d.created | date:"Y-m-d" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary btn-lg">Back</a>
    </div>
  </div>
</div>
{% endblock body %}

my_url/urlshortener/templates/full_list.html
{% extends 'base.html' %} 
{% block body %}

<div class="container">
  <div class="card mt-5">
    <div class="card-header text-center py-3">
      <h1>URL Shortner</h1>
    </div>
    <div class="px-3 py-4">
        <h3>Full list URL</h3>
    </div>
    <div class="px-3 py-4">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Long URL</th>
                        <th>Short URL</th>
                        <th>Created</th>
                        <th>Metrics</th>
                    </tr>
                </thead>
                <tbody>
                    {% for l in full_list %}
                    <tr>
                        <td>{{ l.long_url }}</td>
                        <td>
                            <a href="{% url 'shortener:redirect' l.short_url %}" target="_blank">{{ l.short_url }}</a>
                        </td>
                        <td>{{ l.created | date:"Y-m-d" }}</td>
                        <td>
                            <a href="{% url 'shortener:details' l.pk %}" class="link-primary w-100">More</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <a href="{% url 'shortener:home' %}" class="btn btn-primary btn-lg">Back home</a>
    </div>
  </div>
</div>
{% endblock body %}

my_url/urlshortener/templates/home.html
{% extends 'base.html' %} 
{% block body %}

<div class="container">
  <div class="card mt-5">
    <div class="card-header text-center">
      <h1>URL Shortner</h1>
    </div>
    <div class="px-3 py-3">
      <form action="" method="POST">
        {% csrf_token %}
        <div class="row g-1">
          <div class="col-8">{{form.long_url}}</div>
          <div class="col-2">
            <button class="btn btn-success btn-lg w-100" type="submit">
              Generate
            </button>
          </div>
          <div class="col-2">
            <a class="btn btn-primary btn-lg w-100" href="{% url 'shortener:full_list' %}">
                Full list
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>
  {% if errors %}
  <div class="alert alert-danger" role="alert">
    <p>{{errors}}</p>
  </div>
  {% endif %}

  {% if new_url %}

  <div class="mx-auto text-center mt-5">
    <h2 class="text-danger">Your shortened Url</h2>
    <p>You can copy this link</p>
    <p class="">{{new_url}}</p>
    <p><span class="text-danger">Original URL:</span> {{long_url}}</p>
  </div>
  {% endif %}
</div>
{% endblock body %}